### ISSUE TITLE
Maak je CSS selectors zo breed als mogelijk

### ISSUE THREAD

**Issue by JeroenHeemskerk** [OmerS7/educom-webshop-basis-1693919947#12]
In de code hieronder, heb je een paar selectors die heel specifiek voor bepaalde inputs de breedte zetten.
https://github.com/OmerS7/educom-webshop-basis-1693919947/blob/a4a175ebbb986a2c1620fd918571b945a281fa10/CSS/stylesheet.css#L39-L43
Echter als iemand een andere input toevoegt, zal deze niet deze breedte krijgen. 

Beter is het om bijv. alle inputs een breedte van 400px te geven, en dan eventueel wat uitzonderingen maken voor de submit button en de radio input.
```CSS
 input { 
     width: 400px; 
 }
 
 input[type="submit"], 
 input[type="radio"] { 
     width: auto; 
 }
```
